### PR TITLE
Bug fixes (2) & Enhancements to `Remind` feature

### LINKED ISSUE #119: [PE-D] Reminder remains when client is deleted
Sample ss as follows:

The reminder tab was opened after the client was deleted, but the reminder still exits

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: jaegarpoon/ped#1

### LINKED ISSUE #159: [PE-D] Reminder not cleared for client deleted from list
Reminder is not clear for clients deleted from the list

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: lamwj98/ped#12

### PR DESCRIPTION
**Pull request by waffledood**
# Changes to resolve #159 , #119 

Erroneous behavior of `Remind` feature: 
- Deleting a `Person` who has a `Reminder` set, will not remove their reminder from the Reminders window 

## 
Changes made to resolve these errors: 
- Update the `DeleteCommand` to remove the Person from the `HashMap` storing the `Person` & their `Reminder`s

##
Updated `Remind` feature as follows: 

https://user-images.githubusercontent.com/59903913/161489681-a92d6f3e-1417-4f7a-9cfb-976c31e8c58e.mp4

# Other changes
- Improving the message returned to users in the `ResultDisplay` through more descriptive messages in `MESSAGE_REMIND_PERSON_SUCCESS`, `MESSAGE_UNREMIND_PERSON_SUCCESS`, `MESSAGE_EDIT_REMIND_PERSON_SUCCESS` and `MESSAGE_USAGE` 
- Updated the documentation of various methods in `RemindCommand` 
- Abstracted the message generation to users as a method `generateSuccessMessage` 

##
Updated return messages for `RemindCommand` as follows: 

https://user-images.githubusercontent.com/59903913/161494847-de5a4de5-2b93-4e1a-8195-3532f71852c0.mp4

##
This PR closes #159 , closes #119

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/RemindCommand.java [hunk 1]
```diff
@@ -21,26 +21,35 @@
...
-            + "type \"remind INDEX\"";
-    public static final String MESSAGE_REMIND_PERSON_SUCCESS = "Created Reminder for Person: %1$s";
-    public static final String MESSAGE_UNREMIND_PERSON_SUCCESS = "Removed Reminder for Person: %1$s";
-    public static final String MESSAGE_EDIT_REMIND_PERSON_SUCCESS = "Edited Reminder for Person: %1$s";
+    public static final String MESSAGE_REMIND_PERSON_SUCCESS =
+            "Created Reminder for Client %1$s. He/she is added to the Reminders window.\n"
+            + "If the Reminders window is already open, close it and re-open it \n"
+            + "(via 'rm' command, 'Reminders' button from the 'File' tab, or press 'F4' key) to refresh the data!";
+    public static final String MESSAGE_UNREMIND_PERSON_SUCCESS =
+            "Removed Reminder for Client %1$s. He/She is removed the Reminders window.\n"
```
Comment (hsiaojietng) [inline src/main/java/seedu/address/logic/commands/RemindCommand.java:29]: Nice, I will make these changes for my commands too.

**Review by hsiaojietng — APPROVED** [review]
LGTM!

File: src/main/java/seedu/address/logic/commands/RemindCommand.java (hunk 1 above)
Comment (waffledood) [reply src/main/java/seedu/address/logic/commands/RemindCommand.java:29]: 👍
